config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :wallpapers

    root 'wallpapers#home'

      post 'wallpaper/vote' =>'wallpapers#vote'
      get 'user/:username' => 'user#show'
      get 'user/:username/submitted' => 'user#submitted'
      post 'wallpaper/temp-pic'=>'wallpapers#temp_pic'
      get 'wallpaper/show-tags'=>'wallpapers#show_tags'
      get 'wallpaper/add-tags'=>'wallpapers#add_tags'
      get 'home'=>'wallpapers#home'
      get 'buying-guide'=>'wallpapers#guide'
      get '.well-known/acme-challenge/kpB2nJjAtlD7zc6VDsP093JPQUwL4xlgjxI3wsoLWsA'=>'wallpapers#file1'
      get '.well-known/acme-challenge/9j1ELK2VRcbG0FaGzG2V3412xFXjqT8pF23AR8F6sHY'=>'wallpapers#file2'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 has_attached_file :temp_pic
 validates_attachment_content_type :temp_pic, content_type: /\Aimage/

  has_many :wallpapers
  acts_as_voter
end

app/models/wallpaper.rb
class Wallpaper < ApplicationRecord
  has_attached_file :image,styles: {:thumb=> "1000x1000>"},:convert_options => {
                                                            :thumb => "-quality 80 -interlace Plane"
                                                          }
  validates :title, uniqueness: true
  validates_attachment_content_type :image, content_type: /\Aimage/
  belongs_to :user
  acts_as_votable
  acts_as_taggable # Alias for acts_as_taggable_on :tags

  def to_param
    "#{title}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  require 'will_paginate/array'
  WillPaginate.per_page = 12

  def show
    @user=User.where("username LIKE ?",params[:username])
    @user=@user[0]
    @wallpapers=@user.find_liked_items.paginate(:page => params[:page])
  end
  
  def submitted
    @user=User.where("username LIKE ?",params[:username])
    @user=@user[0]
    @wallpapers=@user.wallpapers.paginate(:page => params[:page])
  end

end

app/controllers/wallpapers_controller.rb
class WallpapersController < ApplicationController
  before_action :set_wallpaper, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, :only => [:temp_pic]
  before_action :authenticate_user!, only: [:new,:edit], notice: 'Sign in First Please'
  require 'will_paginate/array'
  WillPaginate.per_page = 15
  # GET /wallpapers
  # GET /wallpapers.json
  def index
    if params[:color]
      @header=params[:color]
      @wallpapers=Wallpaper.where('color LIKE ?',params[:color]).reverse_order.paginate(:page => params[:page])
    elsif params[:tag]
      @header=params[:tag]
      @wallpapers=[]
      @tags=params[:tag].split(",")
      if params[:tag].end_with? 's'
        @s_wallpapers=Wallpaper.tagged_with([params[:tag].chomp("s")],parse: true, :match_all => false, :any => true).reverse_order
      else
        @s_wallpapers=Wallpaper.tagged_with([params[:tag]+"s"],parse: true, :match_all => false, :any => true).reverse_order
      end
      @non_s_wallpapers=Wallpaper.tagged_with([params[:tag]],parse: true, :match_all => false, :any => true).reverse_order
      @wallpapers=(@non_s_wallpapers+@s_wallpapers).paginate(:page => params[:page])

    else
      @header="Newiest"
      @wallpapers = Wallpaper.all.reverse_order.paginate(:page => params[:page])
    end
  end

  # GET /wallpapers/1
  # GET /wallpapers/1.json
  def show
    if @wallpaper.image.exists? == true
      gon.src= @wallpaper.image.url.to_s
      @size=FastImage.size(@wallpaper.image.url)
    end
  end

  # GET /wallpapers/new
  def new
    @wallpaper = current_user.wallpapers.build
  end

  # GET /wallpapers/1/edit
  def edit
    if current_user != @wallpaper.user
      flash[:error]= 'Thats Not Yours!!'
      redirect_to root_path
    end
  end

  def add_tags
    @new_tags=params[:tags]
    @id=params[:id]
    @wallpaper=Wallpaper.find(@id)
    @wallpaper.tag_list.add(@new_tags,parse: true)
    @wallpaper.save
    redirect_to :back
  end

  # POST /wallpapers
  # POST /wallpapers.json
  def create
    @wallpaper = current_user.wallpapers.build(wallpaper_params.merge(image:current_user.temp_pic))
    respond_to do |format|
      if @wallpaper.save
        current_user.temp_pic.clear
        current_user.save
        format.html { redirect_to @wallpaper, notice: 'Wallpaper was successfully created.' }
        format.json { render :show, status: :created, location: @wallpaper }
      else
        format.html { render :new }
        format.json { render json: @wallpaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallpapers/1
  # PATCH/PUT /wallpapers/1.json
  def update
    respond_to do |format|
      if @wallpaper.update(wallpaper_params)
        format.html { redirect_to @wallpaper, notice: 'Wallpaper was successfully updated.' }
        format.json { render :show, status: :ok, location: @wallpaper }
      else
        format.html { render :edit }
        format.json { render json: @wallpaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallpapers/1
  # DELETE /wallpapers/1.json
  def destroy
    @wallpaper.destroy
    respond_to do |format|
      format.html { redirect_to wallpapers_url, notice: 'Wallpaper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote
    @wallpaper=Wallpaper.find(params[:id])
    if current_user.voted_up_on? @wallpaper
      @wallpaper.unliked_by current_user
    else
      @wallpaper.liked_by current_user
    end


    respond_to do |format|
    format.xml  { render :xml => @wallpaper }
    format.json { render :json => (@wallpaper.get_upvotes.size) }
  end
end
  def temp_pic
    @user=current_user
    @user.temp_pic=params[:file]
    @user.save
    respond_to do |format|
        format.html {  }
        format.json { render json:" @wallpaper.errors, status: :unprocessable_entity "}
    end
  end

  def show_tags
    @tags=ActsAsTaggableOn::Tag.most_used(10000).paginate(:page => params[:page])
  end

  def home

  end
  def guide
  end
  def file1
  end
  def file2
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallpaper
      @wallpaper = Wallpaper.where("title LIKE ?",params[:id]).last
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wallpaper_params
      params.require(:wallpaper).permit(:cat, :color, :picture_id, :title,:image,:tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
      when 'notice' then "alert alert-info alert-dismissable fade in"
      when 'success' then "alert alert-success alert-dismissable fade in"
      when 'error' then "alert alert-danger alert-dismissable fade in"
      when 'alert' then "alert alert-warning alert-dismissable fade in"
    end
  end
end

app/helpers/wallpapers_helper.rb
module WallpapersHelper
end

app/views/layouts/_g_analytics.html.erb
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-91357666-2', 'auto');
</script>

app/views/layouts/_ganalytics_pageview.html.erb
<script>
    ga('send', 'pageview', '<%= request.path %>');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title||= "Ultrawide Wallpapers dedicated for 21:9 3440x1440,2560x1080 Displays!" %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= Gon::Base.render_data %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Audiowide|Exo+2|Oswald" rel="stylesheet">
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
  <%= csrf_meta_tags %>
  <%= render partial: "layouts/g_analytics" %>

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({
      google_ad_client: "ca-pub-3725029270660340",
      enable_page_level_ads: true
    });
  </script>
  
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "UltrawideWallpaper.com",root_path,id:"header_title",class:"navbar-brand"%>
      </div>
      <ul class="nav navbar-nav">
        <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Most Popular Tags
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% ActsAsTaggableOn::Tag.most_used(7).each do |tag|%>
            <li><%= link_to tag,wallpapers_path(:tag=> tag.name )%></li>
          <%end%>
        </ul>
      </li>

      <form action="/wallpapers" method="get" class="navbar-form">
        <div class="form-group" style="display:inline;">
          <div class="input-group">
            <input class="form-control" type="text" id="tag" name="tag" placeholder="search tags">
            <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
          </div>
        </div>
      </form>
        <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Colors
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Black',  wallpapers_path(:color=>'black')  %></li>
          <li><%= link_to 'Blue',  wallpapers_path(:color=>'blue')  %></li>
          <li><%= link_to 'Brown',  wallpapers_path(:color=>'brown')  %></li>
          <li><%= link_to 'Grey',  wallpapers_path(:color=>'grey')  %></li>
          <li><%= link_to 'Green',  wallpapers_path(:color=>'green')  %></li>
          <li><%= link_to 'Orange',  wallpapers_path(:color=>'orange')  %></li>
          <li><%= link_to 'Purple',  wallpapers_path(:color=>'purple')  %></li>
          <li><%= link_to 'Red',  wallpapers_path(:color=>'red')  %></li>
          <li><%= link_to 'White',  wallpapers_path(:color=>'white')  %></li>
          <li><%= link_to 'Yellow',  wallpapers_path(:color=>'yellow')  %></li>
        </ul>
      </li>
      <li><%= link_to "show all tags", wallpaper_show_tags_path ,id:"header_tags_link"%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%if user_signed_in?%>
        <li><%=link_to "/user/#{current_user.username}" do%>
          <i class="glyphicon glyphicon-user"></i> <%=truncate(current_user.username, :length => 9) %>
        <%end%></li>
        <li><%=link_to "/wallpapers/new/" do%>
           New Wallpaper
        <%end%></li>
          <li><%=link_to destroy_user_session_path,method: :delete do%>
            <i class="glyphicon glyphicon-log-out"></i> Logout
          <%end%></li>
        <%else%>
          <li><%=link_to new_user_session_path do%>
            <i class="glyphicon glyphicon-log-in"></i> Login
          <%end%></li>
          <li><%=link_to "/wallpapers/new/" do%>
             New Wallpaper
          <%end%></li>
        <%end%>
      </ul>

    </div>
  </nav>
  
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  </div>
<% end %>
<%= yield %>
<%= render partial: "layouts/ganalytics_pageview" %>

</body>
</html>

app/views/user/show.html.erb
<% @title= "#{@user.username}'s Liked Wallpapers" %>
<h2 id="index_header">Wallpapers Liked by <%=@user.username%></h2>
<% @wallpapers.each do |wallpaper|%>
  <%= render 'wallpapers/gallery',wallpaper: wallpaper %>
<%end%>
<div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @wallpapers %>
  </div>
  <%= will_paginate @wallpapers, :container => false %>
</div>
<%=link_to "#{@user.username}'s Submitted Wallpapers","/user/#{@user.username}/submitted",class:"link"%>
<%= link_to "edit your account",edit_user_registration_path,class:"link" if current_user == @user %>

app/views/user/submitted.html.erb
<% @title= "#{@user.username}'s Submitted Wallpapers" %>
<h2 id="index_header">Wallpapers Submitted by <%=@user.username%></h2>
<% @wallpapers.each do |wallpaper|%>
  <%= render 'wallpapers/gallery',wallpaper: wallpaper %>
<%end%>
<div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @wallpapers %>
  </div>
  <%= will_paginate @wallpapers, :container => false %>
</div>
<%=link_to "#{@user.username}'s liked wallpapers","/user/#{@user.username}",class:"link"%>

app/views/wallpapers/add_tags.html.erb
edit tags
<%= image_tag @wallpaper.image.url,id:"show_wallpaper"%>
<%=@new_tags%>

app/views/wallpapers/home.html.erb
<meta name="description" content="A Site to Find UltraWide 3440x1440,2560x1080 21:9 Wallpapers. Also Sort by Color or by Diffrent Tags! All images are HD and 21:9 aspect ratio.">
<div id="home_1">
  <h1 id="home_h1">Browse 21:9 Wallpapers by Color or Tags with Every Wallpaper Being Designed for Ultrawide Displays!</h1>
  <%= link_to "See All Newiest Wallpapers",wallpapers_path,class:"home_link"%>
</div>
<h1 id="home_h1">Select a Specfic Color Below!</h1>

<div class="parallax">

  <div class="owl-carousel owl-theme">
    <div> <div class="owl_text">BLACK</div><%= link_to (image_tag("black.jpg", alt: "Example Image")),wallpapers_path(:color=>'black')%></div>
    <div> <div class="owl_text">BLUE</div><%= link_to (image_tag("blue.jpg", alt: "Example Image")),wallpapers_path(:color=>'blue')%></div>
    <div> <div class="owl_text">BROWN</div><%= link_to (image_tag("brown.jpg", alt: "Example Image")),wallpapers_path(:color=>'brown')%></div>
    <div> <div class="owl_text">GREEN</div><%= link_to (image_tag("green.jpg", alt: "Example Image")),wallpapers_path(:color=>'green')%></div>
    <div> <div class="owl_text">GREY</div><%= link_to (image_tag("grey.jpg", alt: "Example Image")),wallpapers_path(:color=>'grey')%></div>
    <div> <div class="owl_text">ORANGE</div><%= link_to (image_tag("orange.jpg", alt: "Example Image")),wallpapers_path(:color=>'orange')%></div>
    <div> <div class="owl_text">PURPLE</div><%= link_to (image_tag("purple.jpg", alt: "Example Image")),wallpapers_path(:color=>'purple')%></div>
    <div> <div class="owl_text">RED</div><%= link_to (image_tag("red.jpg", alt: "Example Image")),wallpapers_path(:color=>'red')%></div>
    <div> <div class="owl_text">WHITE</div><%= link_to (image_tag("white.png", alt: "Example Image")),wallpapers_path(:color=>'white')%></div>
    <div> <div class="owl_text">YELLOW</div><%= link_to (image_tag("yellow.jpg", alt: "Example Image")),wallpapers_path(:color=>'yellow')%></div>
  </div>
  <%= link_to "Ultrawide Buying Guide!",buying_guide_path,class:"home_link_2"%>
</div>
<h1 id="home_h1">The Most Used Tags!</h1>
<div class='half one'><%= link_to "NATURE",wallpapers_path(:tag=>"NATURE")%></div>
<div class='half two'><%= link_to "ARTISTIC",wallpapers_path(:tag=>"Artistic")%></div>
<div class='half three'><%= link_to "WATER",wallpapers_path(:tag=>"WATER")%></div>
<div class='half four'><%= link_to "ANIMAL",wallpapers_path(:tag=>"ANIMAL")%></div>
<div class='half five'><%= link_to "CARS",wallpapers_path(:tag=>"CARS")%></div>
<div class='half six'><%= link_to "ARCHITECTURE",wallpapers_path(:tag=>"Architecture")%></div>
<h1 id="home_h1"><%= link_to "See All Tags!", wallpaper_show_tags_path ,id:"home_h1"%></h1>
<div id="long"></div>
<script>
$('.owl-carousel').owlCarousel({
    loop:true,
    nav:true,
    margin:10,
    responsiveClass:true,
    autoplay:true,
    responsive:{
        0:{
            items:1
        },
        1000:{
            items:2
        }
    }
})
</script>

app/views/wallpapers/show.html.erb
<meta name="description" content="A Site to Find UltraWide 3440x1440,2560x1080 21:9 Wallpapers. Also Sort by Color or by Diffrent Tags! All images are HD and 21:9 aspect ratio.">
<h2 id="wallpaper_title_show"><%= @wallpaper.title %> Ultrawide Wallpaper</h2>
<h4 id="wallpaper_h4">submitted by <%=link_to @wallpaper.user.username,"/user/#{@wallpaper.user.username}"%></h4>
<%= image_tag @wallpaper.image.url,id:"show_wallpaper",alt:"#{@wallpaper.title} Ultrawide Wallpaper"%>
<div id="show_tags">
  <strong>&nbsp;&nbsp;Tags:</strong><br>
  <ul>
  <% @wallpaper.tag_list.each do |tag|%>
    <li><%=link_to tag,wallpapers_path(:tag=> tag )%></li>
  <%end%>
  </ul>
</div>
<div id="show_color">
  <strong>Color:</strong>
  <%= if @wallpaper.color == "" then "???" else link_to @wallpaper.color, wallpapers_path(:color=>@wallpaper.color),id:"color_link" end %>
</div>
<div id="resolution">
  Resolution:<br><%=@size[0]%>x<%=@size[1]%>
</div>
<% if user_signed_in?%>
  <div id="rating_div">
    <%= link_to "javascript:void(0)", class: "like #{'liked' if current_user.voted_up_on? @wallpaper}",id:@wallpaper.id do %>
       <i class="glyphicon glyphicon-star"></i>
    <% end %>
    <p id="p_like"><%=if current_user.voted_up_on? @wallpaper then "Like!"else "Like?" end%></p>
    <br>Amount of Likes:
    <div class="rating">
      <%= @wallpaper.get_upvotes.size%>
    </div>
  </div>
<%else%>
  <div id="rating_div">
    Amount of Likes:
    <div class="rating">
      <%= @wallpaper.get_upvotes.size%>
    </div>
  </div>
<%end%>
<% if current_user == @wallpaper.user%>
  <%= link_to 'Delete', @wallpaper, method: :delete, data: { confirm: 'Are you sure?' },class:"link" %>
  <%= link_to 'Edit Your Wallpaper',edit_wallpaper_path(@wallpaper),class:"link" %>
<%else%>
  <h4 id="tags_h4">add more tags!</h4>
  <%= form_tag wallpaper_add_tags_path, method: :get,class:"add_tags_form" do %>
      <%= hidden_field_tag 'id', @wallpaper.id%>
      <%=text_field_tag 'tags',"",placeholder:"ex.'nature,shepard puppy'"%><br>
      <span class="help-block">seperate tags with a comma (ex.'nature,shepard puppy,doggie')</span>
      <%=submit_tag "add tags"%>
  <%end%>
<%end%>




<script>
$('.like').click(function(e) {
  console.log("CLICKED");
  var wallpaper= $(this).attr("id")
  $(this).toggleClass( "liked" );
  $.ajax({
    type: "POST",
    url: "/wallpaper/vote",
    dataType:"json",
    data: {id:wallpaper },
    success:function(data) {
      console.log(data);
      $(".rating").text(data)
      var text= $("#p_like").text()
      if(text=="Like?"){
        $("#p_like").text("Like!")
      }else{
        $("#p_like").text("Like?")
      }
      return false;
    },
    error:function(data) {
      console.log("error");
      return false;
    }
  });
});
$('#show_wallpaper').magnificPopup({
  items: {
    src: gon.src
  },
  type: 'image',
  closeOnContentClick: true,
  mainClass: 'mfp-with-zoom', // this class is for CSS animation below

  zoom: {
    enabled: true, // By default it's false, so don't forget to enable it

    duration: 300, // duration of the effect, in milliseconds
    easing: 'ease-in-out', // CSS transition easing function

    // The "opener" function should return the element from which popup will be zoomed in
    // and to which popup will be scaled down
    // By defailt it looks for an image tag:
    opener: function(openerElement) {
      // openerElement is the element on which popup was initialized, in this case its <a> tag
      // you don't need to add "opener" option if this code matches your needs, it's defailt one.
      return $('#show_wallpaper');
    }
  }
});

$(document).ready(function () {

  $.validate({
    lang: 'en',
    modules : 'security,html5',
    onSuccess : function($form) {
    },
    onError : function($form) {
      console.log("error");
      sweetAlert("Opps!", "Something Was Wrong", "warning");
      return false; // IF FALSE Will stop the submission of the form
    }

  });

});
</script>

app/views/wallpapers/showBACKUP.html.erb
<meta name="description" content="A Site to Find UltraWide 3440x1440,2560x1080 21:9 Wallpapers. Also Sort by Color or by Diffrent Tags! All images are HD and 21:9 aspect ratio.">
<h2 id="wallpaper_title_show"><%= @wallpaper.title %> Ultrawide Wallpaper</h2>
<h4 id="wallpaper_h4">submitted by <%=link_to @wallpaper.user.username,"/user/#{@wallpaper.user.username}"%></h4>
<%= image_tag @wallpaper.image.url,id:"show_wallpaper",alt:"#{@wallpaper.title} Ultrawide Wallpaper"%>
<div id="show_tags">
  <strong>&nbsp;&nbsp;Tags:</strong><br>
  <ul>
  <% @wallpaper.tag_list.each do |tag|%>
    <li><%=link_to tag,wallpapers_path(:tag=> tag )%></li>
  <%end%>
  </ul>
</div>
<div id="show_color">
  <strong>Color:</strong>
  <%= if @wallpaper.color == "" then "???" else link_to @wallpaper.color, wallpapers_path(:color=>@wallpaper.color),id:"color_link" end %>
</div>
<div id="resolution">
  Resolution:<br><%=@size[0]%>x<%=@size[1]%>
</div>
<% if user_signed_in?%>
  <div id="rating_div">
    <%= link_to "javascript:void(0)", class: "like #{'liked' if current_user.voted_up_on? @wallpaper}",id:@wallpaper.id do %>
       <i class="glyphicon glyphicon-star"></i>
    <% end %>
    <p id="p_like"><%=if current_user.voted_up_on? @wallpaper then "Like!"else "Like?" end%></p>
    <br>Amount of Likes:
    <div class="rating">
      <%= @wallpaper.get_upvotes.size%>
    </div>
  </div>
<%else%>
  <div id="rating_div">
    Amount of Likes:
    <div class="rating">
      <%= @wallpaper.get_upvotes.size%>
    </div>
  </div>
<%end%>
<% if current_user == @wallpaper.user%>
  <%= link_to 'Delete', @wallpaper, method: :delete, data: { confirm: 'Are you sure?' },class:"link" %>
  <%= link_to 'Edit Your Wallpaper',edit_wallpaper_path(@wallpaper),class:"link" %>
<%else%>
  <h4 id="tags_h4">add more tags!</h4>
  <%= form_tag wallpaper_add_tags_path, method: :get,class:"add_tags_form" do %>
      <%= hidden_field_tag 'id', @wallpaper.id%>
      <%=text_field_tag 'tags',"",placeholder:"ex.'nature,shepard puppy'"%><br>
      <span class="help-block">seperate tags with a comma (ex.'nature,shepard puppy,doggie')</span>
      <%=submit_tag "add tags"%>
  <%end%>
<%end%>




<script>
$('.like').click(function(e) {
  console.log("CLICKED");
  var wallpaper= $(this).attr("id")
  $(this).toggleClass( "liked" );
  $.ajax({
    type: "POST",
    url: "/wallpaper/vote",
    dataType:"json",
    data: {id:wallpaper },
    success:function(data) {
      console.log(data);
      $(".rating").text(data)
      var text= $("#p_like").text()
      if(text=="Like?"){
        $("#p_like").text("Like!")
      }else{
        $("#p_like").text("Like?")
      }
      return false;
    },
    error:function(data) {
      console.log("error");
      return false;
    }
  });
});
$('#show_wallpaper').magnificPopup({
  items: {
    src: gon.src
  },
  type: 'image',
  closeOnContentClick: true,
  mainClass: 'mfp-with-zoom', // this class is for CSS animation below

  zoom: {
    enabled: true, // By default it's false, so don't forget to enable it

    duration: 300, // duration of the effect, in milliseconds
    easing: 'ease-in-out', // CSS transition easing function

    // The "opener" function should return the element from which popup will be zoomed in
    // and to which popup will be scaled down
    // By defailt it looks for an image tag:
    opener: function(openerElement) {
      // openerElement is the element on which popup was initialized, in this case its <a> tag
      // you don't need to add "opener" option if this code matches your needs, it's defailt one.
      return $('#show_wallpaper');
    }
  }
});

$(document).ready(function () {

  $.validate({
    lang: 'en',
    modules : 'security,html5',
    onSuccess : function($form) {
    },
    onError : function($form) {
      console.log("error");
      sweetAlert("Opps!", "Something Was Wrong", "warning");
      return false; // IF FALSE Will stop the submission of the form
    }

  });

});
</script>

app/views/wallpapers/show_tags.html.erb
<% @title= "Tags for Ultrawide Wallpapers" %>
<meta name="description" content="All The Tags to Find The Right UltraWide 3440x1440,2560x1080 21:9 Wallpapers!">
<div id="tags_containter">
<%@tags.each do |tag|%>
  <div class="tag_listing">
    <%@wallpaper=Wallpaper.tagged_with(tag.name).limit(1)%>
    <%= image_tag @wallpaper[0].image.url(:thumb),class:"tags_pics"%>
    <br><%=link_to tag.name,wallpapers_path(:tag=> tag.name )%> (<%=(tag.taggings_count)%>)
  </div>
<%end%>
</div>
<div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @tags %>
  </div>
  <%= will_paginate @tags, :container => false %>
</div>